name: build-test
on: push
jobs:
  build-job:
    runs-on: ubuntu:latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '18.x'
      - name: install dependecies
        run: npm install
      - name: test application
        run: npm run build
  test-job:
      needs: build-job
      runs-on: ubuntu:latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: install node
          uses: actions/setup-node@v3.9.1
          with:
            node-version: '18.x'
        - name: install dependecies
          run: npm install
        - name: test application
          run: npm run build
  deploy-job:
    needs: build-job
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install dependecies
        run: npm install
      - name: build application
        run: npm run build
      - name: configure pages
        uses: action/upload-pages-artifact@v3
        with:
          path: "./out"
      - name: display
      
        
      
