name: build-test
on: push
jobs:
  build-job:
    runs-on: ubuntu:latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '18.x'
      - name: install dependecies
        run: npm install
      - name: test application
        run: npm run build
  test-job:
      needs: build-job
      runs-on: ubuntu:latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: install node
          uses: actions/setup-node@v3.9.1
          with:
            node-version: '18.x'
        - name: install dependecies
          run: npm install
        - name: test application
          run: npm run build
        
