name: Read Secret
on: push
jobs: 
  read-secret-job:
    runs-on: ubuntu:latest
    env: 
      MY_ENV_VAR: "dit is een nieuwe environment variabele"
    steps:
      - name: print the secret
        run: echo "my secret is ${{ secrets.MY_SECRET }}"
      - name: print environment variabele
        run: echo "env var is $MY_ENV_VAR"
